#!/bin/bash
# Quick Commands Reference for MkweliMobile

echo "╔════════════════════════════════════════════════════════════╗"
echo "║           MkweliMobile - Quick Command Reference          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🚀 BUILD & RUN (Automated):"
echo "   cd ~/MkweliMobile && ./build-and-run.sh"
echo ""
echo "🔨 BUILD ONLY:"
echo "   cd ~/MkweliMobile/android && ./gradlew assembleDebug"
echo ""
echo "📱 INSTALL & LAUNCH:"
echo "   adb install -r android/app/build/outputs/apk/debug/app-debug.apk"
echo "   npm start &"
echo "   sleep 10"
echo "   adb shell am start -n com.mkwelimobile/.MainActivity"
echo ""
echo "🧹 CLEAN BUILD:"
echo "   cd ~/MkweliMobile/android && ./gradlew clean && ./gradlew assembleDebug"
echo ""
echo "📊 CHECK STATUS:"
echo "   adb devices                    # Check emulator"
echo "   adb logcat | grep -i mkweli    # View app logs"
echo "   ls -lh android/app/build/outputs/apk/debug/app-debug.apk  # Check APK"
echo ""
echo "🔄 RESTART:"
echo "   pkill -f 'react-native start'  # Kill Metro"
echo "   npm start &                    # Restart Metro"
echo "   adb shell am start -n com.mkwelimobile/.MainActivity"
echo ""
echo "🛑 UNINSTALL:"
echo "   adb uninstall com.mkwelimobile"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
